apiVersion: v2
name: camunda-platform
version: 10.1.0
appVersion: 8.5.x
description: |
  Camunda 8 Self-Managed Helm charts.
  Camunda's process automation platform allows developers to design, automate and improve processes.
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
home: https://docs.camunda.io/docs/self-managed/overview/
sources:
  - https://github.com/camunda/camunda-platform-helm
keywords:
  - bpm
  - bpmn
  - camunda-platform
  - dmn
  - process-engine
  - workflow
dependencies:
  # Identity Dependencies.
  - name: keycloak
    alias: identityKeycloak
    repository: https://charts.bitnami.com/bitnami
    version: 19.4.1
    condition: "identity.keycloak.enabled,identityKeycloak.enabled"
  - name: postgresql
    alias: identityPostgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.x.x
    condition: "identity.postgresql.enabled,identityPostgresql.enabled"
  # WebModeler Dependencies.
  - name: web-modeler-postgresql
    alias: postgresql
    repository: "file://../web-modeler-postgresql"
    version: 11.x.x
    condition: "postgresql.enabled"
  # Shared Dependencies.
  - name: elasticsearch
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 21.2.3
    condition: "elasticsearch.enabled"
  # Helpers.
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.x.x
maintainers:
  - name: Zelldon
    email: christopher.zell@camunda.com
  - name: aabouzaid
    email: ahmed.abouzaid@camunda.com
annotations:
  camunda.io/helmCLIVersion: "3.15.1"
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: "warning and error for not setting existingSecrets for all components"
    - kind: added
      description: "support envFrom reference in all components"
    - kind: added
      description: "adding a constraint for identity existingSecret"
    - kind: fixed
      description: "release info did not respect the context path"
    - kind: fixed
      description: "update livenessProbe endpoint of zeebe"
    - kind: fixed
      description: "re-added the postgresql secret"
    - kind: fixed
      description: "Delete multi-region review comment in values.yaml"
    - kind: fixed
      description: "use component service account"
    - kind: fixed
      description: "handle type of es url correctly"
    - kind: fixed
      description: "set zeebe exporters empty map when disabled"
    - kind: fixed
      description: "add constraints for when identity is disabled and keycloak is enabled"
    - kind: changed
      description: "add support for seccomp profiles in all components"
    - kind: changed
      description: "update identity application yaml to match upstream"
