name: "Dispatch Backport - Integration - Main"

on:
  workflow_dispatch:
    inputs:
      ttl:
        description: |
          Define a ttl for the lifespan of the workflow
        required: false
        default: ""
        type: string
      platforms:
        description: platform to test on
        required: false
        default: gke
        type: string
      identifier:
        description: The unique identifier of used in the deployment hostname.
        required: true
        type: string
      extra-values:
        description: Pass extra values to the Helm chart.
        required: false
        type: string

permissions:
      contents: read
   
jobs:
  helm-deploy:
    name: Helm chart Integration Tests
    permissions:
      contents: read
      id-token: write
      deployments: write
    uses: ./.github/workflows/test-integration-main.yaml
    secrets: inherit
    with:
      identifier: ${{ github.event.inputs.identifier }}
      extra-values: ${{ github.event.inputs.extra-values }}
      platforms: ${{ github.event.inputs.platforms }}
      ttl: ${{ github.event.inputs.ttl == "1w" }}
