name: "Test - Integration"

on:
  pull_request:
    paths:
    - '.github/workflows/test-integration-template.yaml'
    - '.github/workflows/test-integration.yaml'
    - '.github/actions/gke-login/**'
    - '.github/actions/workflow-vars/**'
    - '.tool-versions'
    - 'charts/camunda-platform-latest/**'
    - 'charts/camunda-platform-alpha/**'
    types: [opened, closed, reopened, synchronize]

permissions:
  contents: read

jobs:
  test:
    name: Main
    permissions:
      contents: read
      id-token: write
      deployments: write
    secrets: inherit
    uses: ./.github/workflows/test-integration-template.yaml
    with:
      identifier: "${{ github.event.pull_request.number }}"
      platforms: "gke,rosa"
      repo: "camunda-platform-helm"
      ttl: "${{ contains(github.event.pull_request.labels.*.name, 'test-persistent') && '1w' || '' }}"
      flows: "install,upgrade"
      caller-git-ref: ${{ github.event.pull_request.head.sha }}
      camunda-helm-git-ref: ${{ github.event.pull_request.head.sha }}
