# Docs: https://github.com/camunda/camunda-platform-helm/blob/main/docs/gha-workflows.md
name: "Test - Integration - Template"

on:
  workflow_call:
    inputs:
      identifier:
        description: The unique identifier of used in the deployment hostname.
        required: true
        type: string
      camunda-helm-dir:
        required: false
        default: camunda-platform-latest
        type: string
      camunda-helm-git-ref:
        required: false
        default: main
        type: string
      caller-git-ref:
        required: false
        default: main
        type: string
      ttl:
        description: |
          Define a ttl for the lifespan of the workflow
        required: false
        default: ""
        type: string
      repo:
        description: |
          Specifies what github repository has called this workflow
        required: false
        default: ""
        type: string
      platforms:
        default: gke
        type: string
      flows:
        required: false
        default: install
        type: string
      test-enabled:
        required: false
        default: true
        type: boolean
      extra-values:
        description: Pass extra values to the Helm chart.
        required: false
        type: string
      vault-secret-mapping:
        description: (optional) defines how to map Vault secrets to distro CI environment variables
        required: false
        type: string

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ inputs.identifier }}
  cancel-in-progress: true

env:
  # Vars with "CI_" prefix are used in the CI workflow only.
  # Vars with "TEST_" prefix are used in the test runner tool (Task).
  CI_TTL: ${{ inputs.ttl }}
  REPO: ${{ inputs.repo }}
  CI_HOSTNAME_BASE: ci.distro.ultrawombat.com
  # Docker Hub auth to avoid image pull rate limit.
  TEST_CREATE_DOCKER_LOGIN_SECRET: "TRUE"
  TEST_DOCKER_USERNAME: ${{ secrets.DISTRO_CI_DOCKER_USERNAME_DOCKERHUB }}
  TEST_DOCKER_PASSWORD: ${{ secrets.DISTRO_CI_DOCKER_PASSWORD_DOCKERHUB }}
  # Camunda registry auth to access WebModeler Docker image since it's not public.
  TEST_DOCKER_USERNAME_CAMUNDA_CLOUD: ${{ secrets.DISTRO_CI_DOCKER_USERNAME_CAMUNDA }}
  TEST_DOCKER_PASSWORD_CAMUNDA_CLOUD: ${{ secrets.DISTRO_CI_DOCKER_PASSWORD_CAMUNDA }}

jobs:
  test:
    name: ${{ matrix.distro.name }} - ${{ matrix.scenario.name }}
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      deployments: write
    strategy:
      fail-fast: false
      matrix:
        distro:
        - name: Kubernetes 1.27
          type: kubernetes
          platform: gke
          secret:
            cluster-name: DISTRO_CI_GCP_GKE_CLUSTER_NAME
            cluster-location: DISTRO_CI_GCP_GKE_CLUSTER_LOCATION
            workload-identity-provider: DISTRO_CI_GCP_WORKLOAD_IDENTITY_PROVIDER
            service-account: DISTRO_CI_GCP_SERVICE_ACCOUNT
          if: ${{ contains(inputs.platforms, 'gke') }}
        - name: OpenShift 4.14
          type: openshift
          version: 4.14
          platform: rosa
          secret:
            server-url: DISTRO_CI_OPENSHIFT_CLUSTER_URL
            username: DISTRO_CI_OPENSHIFT_CLUSTER_USERNAME
            password: DISTRO_CI_OPENSHIFT_CLUSTER_PASSWORD
          if: ${{ contains(inputs.platforms, 'rosa') }}
        scenario:
        - name: Chart Setup
          desc: Setup chart in production-like setup with Ingress and TLS.
          flow: install
          if: ${{ contains(inputs.flows, 'install') }}
        - name: Chart Upgrade
          desc: Upgrade chart from the latest released version to the current branch.
          flow: upgrade
          if: ${{ contains(inputs.flows, 'upgrade') }}
        exclude:
        - distro:
            if: false
        - scenario:
            if: false

    env:
      TEST_CLUSTER_TYPE: ${{ matrix.distro.type }}

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        # This is needed to load repo GH composite actions if the workflow triggered by workflow_call.
        repository: camunda/camunda-platform-helm
        ref: ${{ inputs.camunda-helm-git-ref }}

    # When there is a vault-secret-mapping input given, use Vault instead of GitHub secrets
    # and populate environment variables from Vault
    - name: Import Vault secrets
      id: secrets
      uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3.0.0
      if: inputs.vault-secret-mapping != ''
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: ${{ inputs.vault-secret-mapping }}
        exportEnv: true

    # Used to create/delete GitHub environment.
    # NOTE: The GH app requires "administration:write" access to be able to delete the GH environment.
    - name: Generate GitHub token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
      id: generate-github-token
      with:
        app_id: ${{ secrets.GH_APP_ID_DISTRO_CI_MANAGE_GH_ENVS }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY_DISTRO_CI_MANAGE_GH_ENVS }}
    # TODO: Later, find a way to abstract the auth for different platforms.
    - name: Authenticate to GKE
      if: matrix.distro.platform == 'gke'
      uses: ./.github/actions/gke-login
      with:
        cluster-name: ${{ secrets[matrix.distro.secret.cluster-name] }}
        cluster-location: ${{ secrets[matrix.distro.secret.cluster-location] }}
        workload-identity-provider: ${{ secrets[matrix.distro.secret.workload-identity-provider] }}
        service-account: ${{ secrets[matrix.distro.secret.service-account] }}
    - name: Authenticate to OpenShift
      if: matrix.distro.platform == 'rosa'
      uses: redhat-actions/oc-login@5eb45e848b168b6bf6b8fe7f1561003c12e3c99d # v1
      with:
        openshift_server_url: ${{ secrets[matrix.distro.secret.server-url] }}
        openshift_username: ${{ secrets[matrix.distro.secret.username] }}
        openshift_password: ${{ secrets[matrix.distro.secret.password] }}
    - name: Set workflow vars
      id: vars
      uses: ./.github/actions/workflow-vars
      with:
        ttl: ${{ env.CI_TTL }}
        repo: ${{ env.REPO }}
        setup-flow: ${{ matrix.scenario.flow }}
        platform: ${{ matrix.distro.platform }}
        identifier-base: ${{ inputs.identifier }}
        ingress-hostname-base: ${{ env.CI_HOSTNAME_BASE }}
        chart-dir: ${{ inputs.camunda-helm-dir }}
    - name: Set test type vars
      id: test-type-vars
      uses: ./.github/actions/test-type-vars
      with:
        chart-dir: "${{ inputs.camunda-helm-dir }}"
    - name: Install env dependencies
      uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
    - name: Add Helm repos and dependencies
      run: |
        export chartPath="charts/${{ inputs.camunda-helm-dir }}"
        make helm.repos-add
        make helm.dependency-update
    - name: Create test namespace
      run: |
        echo $TEST_NAMESPACE
        kubectl delete ns --ignore-not-found=true \
          -l "github-id=${{ steps.vars.outputs.identifier }},test-flow=${{ matrix.scenario.flow }}"
        kubectl create ns $TEST_NAMESPACE
        kubectl label ns $TEST_NAMESPACE github-run-id=$GITHUB_WORKFLOW_RUN_ID
        kubectl label ns $TEST_NAMESPACE github-job-id=$GITHUB_WORKFLOW_JOB_ID
        kubectl label ns $TEST_NAMESPACE github-id=${{ steps.vars.outputs.identifier }}
        kubectl label ns $TEST_NAMESPACE test-flow=${{ matrix.scenario.flow }}
        kubectl label ns $TEST_NAMESPACE repo=${{ env.REPO }}
        kubectl annotate ns $TEST_NAMESPACE cleaner/ttl=${{ env.CI_TTL }}
    - name: Copy PRs wildcard certificate
      run: |
        kubectl apply -n $TEST_NAMESPACE -f .github/config/external-secret.yaml
    - name: Start GitHub deployment
      uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8 # v1
      id: deployment
      with:
        step: start
        token: ${{ steps.generate-github-token.outputs.token }}
        env: ${{ steps.vars.outputs.identifier }}
        ref: ${{ inputs.caller-git-ref }}
    - name: Pre setup
      timeout-minutes: 5
      env:
        TEST_CHART_FLOW: ${{ matrix.scenario.flow }}
        TEST_INGRESS_HOST: ${{ steps.vars.outputs.ingress-host }}
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup setup.pre

        echo "Extra values from workflow:"
        echo "${{ inputs.extra-values }}" > /tmp/extra-values-file.yaml
        cat /tmp/extra-values-file.yaml
    - name: 🌟 Setup Camunda chart 🌟
      env:
        TEST_CHART_FLOW: ${{ matrix.scenario.flow }}
        TEST_HELM_EXTRA_ARGS: >-
          --set global.ingress.host=${{ steps.vars.outputs.ingress-host }}
          --values /tmp/extra-values-file.yaml
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup setup.exec
    - name: Post setup
      timeout-minutes: 5
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup setup.post
    - name: Pre Upgrade
      if: matrix.scenario.flow == 'upgrade'
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup upgrade.pre
    - name: 🌟 Upgrade Camunda chart 🌟
      if: matrix.scenario.flow == 'upgrade'
      env:
        TEST_HELM_EXTRA_ARGS: >-
          --set global.ingress.host=${{ steps.vars.outputs.ingress-host }}
          --values /tmp/extra-values-file.yaml
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup upgrade.exec
    - name: Update GitHub deployment status
      uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8 # v1
      with:
        step: finish
        token: ${{ steps.generate-github-token.outputs.token }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        env_url: https://${{ steps.vars.outputs.ingress-host }}
        env: ${{ steps.vars.outputs.identifier }}
        ref: ${{ inputs.caller-git-ref }}
    - name: ⭐️ Run Preflight TestSuite ⭐️
      if: inputs.test-enabled
      timeout-minutes: 10
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup test.preflight
    - name: ⭐️ Run Core TestSuite ⭐️
      if: inputs.test-enabled
      timeout-minutes: 20
      run: |
        task -d ${CI_TASKS_BASE_DIR}/chart-full-setup test.core
    - name: 🚨 Get failed Pods info 🚨
      if: failure()
      uses: ./.github/actions/failed-pods-info
    - name: Cleanup GitHub deployment
      if: always() && (env.CI_TTL != "" || matrix.distro.type != 'kubernetes')
      uses: bobheadxi/deployments@648679e8e4915b27893bd7dbc35cb504dc915bc8 # v1
      with:
        step: delete-env
        token: ${{ steps.generate-github-token.outputs.token }}
        env: ${{ steps.vars.outputs.identifier }}
        ref: ${{ inputs.caller-git-ref }}
    - name: Cleanup test namespace
      if: always() && (env.CI_TTL != "" || matrix.distro.type != 'kubernetes')
      run: |
        kubectl delete ns --ignore-not-found=true \
          -l github-run-id=$GITHUB_WORKFLOW_RUN_ID \
          -l github-job-id=$GITHUB_WORKFLOW_JOB_ID
